services:
  zeek1:
    build:
      context: ./
      dockerfile: ./src/Dockerfile
      args:
        LIBRDKAFKA_VERSION: 2.0.0
        ZEEK_KAFKA_VERSION: 0.1.0
    cap_add:
      - NET_ADMIN
    network_mode: host
    environment:
      - CONTAINER_NAME=zeek1
    volumes:
      - ./config.yaml:/opt/config.yaml
      - ./data/test_pcaps/:/opt/static_files
